[options]
   UseSyslog

[opencloseSSH]
   sequence      = 1950,7777,10502
   seq_timeout   = 10
   tcpflags      = syn
   start_command = iptables -I INPUT -s %IP% -p tcp --dport 22 -j ACCEPT
   cmd_timeout   = 30
   stop_command  = iptables -D INPUT -s %IP% -p tcp --dport 22 -j ACCEPT
